---
- hosts: all
  become: true
  tasks:
    - name: Create keyrings directory
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Download and add Kubernetes GPG key
      shell: |
        curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.32/deb/Release.key | gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
      args:
        creates: /etc/apt/keyrings/kubernetes-apt-keyring.gpg

    - name: Remove Kubernetes repository file
      ansible.builtin.file:
        path: /etc/apt/sources.list.d/kubernetes.list
        state: absent

    - name: Add a fresh new copy Kubernetes repository to apt sources
      ansible.builtin.lineinfile:
        path: /etc/apt/sources.list.d/kubernetes.list
        line: 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.32/deb/ /'
        create: yes

    - name: Update apt cache
      apt:
        update_cache: yes


    - name: Install Kubernetes packages
      apt:
        name:
          - kubeadm
          - kubectl
          - kubelet
        state: present

- hosts: control
  become: true
  tasks:
    - name: Initialize Kubernetes cluster
      # shell: kubeadm init --control-plane-endpoint={{ hostvars[groups['control'][0]]['ansible_default_ipv4']['address'] }} --node-name controller --pod-network-cidr=10.244.0.0/16
      shell: kubeadm init --control-plane-endpoint={{ hostvars[groups['control'][0]]['ansible_default_ipv4']['address'] }} --node-name {{ inventory_hostname }} --pod-network-cidr=10.244.0.0/16
      args:
        creates: /etc/kubernetes/admin.conf
      register: kubeadm_init

    - name: Create .kube directory
      file:
        path: $HOME/.kube
        state: directory
        mode: '0755'

    - name: Copy admin.conf to user's kube config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: $HOME/.kube/config
        remote_src: yes
      when: kubeadm_init.changed

    - name: Change ownership of .kube/config
      file:
        path: $HOME/.kube/config
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_id }}"
      when: kubeadm_init.changed

    - name: Install Flannel overlay network
      shell: kubectl apply -f https://raw.githubusercontent.com/flannel-io/flannel/master/Documentation/kube-flannel.yml
      when: kubeadm_init.changed

    - name: Get join command
      shell: kubeadm token create --print-join-command
      register: join_command
      when: kubeadm_init.changed

    - name: Copy join command to local file
      local_action: copy content="{{ join_command.stdout_lines[0] }}" dest="./join-command"
      when: kubeadm_init.changed

- hosts: nodes
  become: true
  tasks:
    - name: Copy join command from local file
      copy:
        src: ./join-command
        dest: /tmp/join-command.sh
        mode: '0777'

    - name: Join the cluster
      command: sh /tmp/join-command.sh
      register: join_cluster
      changed_when: join_cluster.rc == 0
      failed_when: join_cluster.rc != 0 and "This node has already been joined to the cluster" not in join_cluster.stderr

- hosts: control
  become: true
  tasks:
    - name: Create pod.yml
      copy:
        content: |
          apiVersion: v1
          kind: Pod
          metadata:
            name: nginx-example
            labels:
              app: nginx
          spec:
            containers:
              - name: nginx
                image: linuxserver/nginx
                ports:
                  - containerPort: 80
                    name: "nginx-http"
        dest: /home/{{ ansible_user }}/pod.yml

    - name: Apply pod.yml
      command: kubectl apply -f /home/{{ ansible_user }}/pod.yml

    - name: Create service-nodeport.yml
      copy:
        content: |
          apiVersion: v1
          kind: Service
          metadata:
            name: nginx-example
          spec:
            type: NodePort
            ports:
              - name: http
                port: 80
                nodePort: 30080
                targetPort: nginx-http
            selector:
              app: nginx
        dest: /home/{{ ansible_user }}/service-nodeport.yml

    - name: Apply service-nodeport.yml
      command: kubectl apply -f /home/{{ ansible_user }}/service-nodeport.yml
